/*
 * TestPsodaPanelJFrame.java
 *
 * Created on March 14, 2008, 12:24 AM
 */

package treesaap.Driver;

import treesaap.GraphicInterface.Panels.MainPanel5;

/**
 *
 * @author  Jay
 */
public class TestPsodaPanelJFrame extends javax.swing.JFrame {
    
    /** Creates new form TestPsodaPanelJFrame */
    public TestPsodaPanelJFrame() {
        String filename = "./SampleData/treesaap.nex";
        getContentPane().add(new MainPanel5(), java.awt.BorderLayout.CENTER);

        initComponents();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TreeSAAP in Psoda Preview Frame");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestPsodaPanelJFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
