/*
 * Copyright (C) <2009> <Quinn Snell, Mark Clement>
 *
 * This program is free software; you can redistribute it and/or modify it under the 
 * terms of the GNU General Public License as published by the Free Software Foundation; 
 * either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program (gpl.txt); 
 * if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 * More information can be obtained by accessing http://dna.cs.byu.edu/psoda
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gui_GuiCommandNode */

#ifndef _Included_gui_GuiCommandNode
#define _Included_gui_GuiCommandNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gui_GuiCommandNode
 * Method:    runCommand
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gui_GuiCommandNode_runCommand
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gui_GuiCommandNode
 * Method:    toCode
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gui_GuiCommandNode_toCode
  (JNIEnv *, jclass, jstring, jobjectArray, jobjectArray);

/*
 * Class:     gui_GuiCommandNode
 * Method:    getParamNames
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_gui_GuiCommandNode_getParamNames
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gui_GuiCommandNode
 * Method:    getParamDescriptions
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_gui_GuiCommandNode_getParamDescriptions
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gui_GuiCommandNode
 * Method:    getParamOptions
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_gui_GuiCommandNode_getParamOptions
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     gui_GuiCommandNode
 * Method:    getFileParamNames
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_gui_GuiCommandNode_getFileParamNames
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gui_GuiCommandNode
 * Method:    getDefaultValues
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_gui_GuiCommandNode_getDefaultValues
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
