#!/usr/bin/python

import SodaSconsUtil

Import ( 'env', 'soda' )

EXCLUSIONS      = []
LIBRARY_NAME    = soda['UTILITY_LIB_NAME']

SOURCELIST      = SodaSconsUtil.listCPPFilesWithExcludes ( ".", EXCLUSIONS )
INCLUDEFILELIST = SodaSconsUtil.listIncludeFiles ( "." )
LIBS            = soda['UTILITY_LIB_DEPENDENCIES']

env.SharedLibrary ( target = LIBRARY_NAME , source = SOURCELIST , LIBS = LIBS )

