default: build_all

build_all :
	javac BASEML/*.java Block/*.java CDM/*.java CommandLine/*.java Data/*.java Driver/*.java Evpthwy/*.java GeneralDNAFileParser/*.java GraphicInterface/*.java GraphicInterface/Objects/*.java GraphicInterface/Panels/*.java Objects/*.java Run/*.java Substs/*.java Tree/*.java Weka/*.java -cp jxl.jar:EDU.jar:byu.jar:swing-layout-1.0.3.jar

